packages:
  - name: default
    actions:
      - name: hello
        main: lambda_handler
        environment:
          SIGNALFX_INGEST_ENDPOINT: ${SIGNALFX_INGEST_ENDPOINT}
          SIGNALFX_ACCESS_TOKEN: ${SIGNALFX_ACCESS_TOKEN}
