packages:
  - name: default
    actions:
      - name: hello
        main: lambda_handler
        environment:
          SIGNALFX_INGEST_ENDPOINT: "https://ingest.us1.signalfx.com"
          SIGNALFX_ACCESS_TOKEN: ${SIGNALFX_ACCESS_TOKEN}
